Compile string literals as stdlib Strings
trill-lang/trill pull request #33
Opened 2017-03-04 05:35 UTC by segiddins

- [ ] Update stdlib
- [ ] Update examples
- [ ] Ship the stdlib inside the runtime framework
- [ ] Make detecting stdlib presence more robust
- [ ] Allow string literals to be coerced to `*Int`s?

2017-03-04 05:36 UTC, harlanhaskins commented
I'd say definitely -- if we can demote a `String` to `*Int8` automatically it'll help interface with C tremendously.

2017-03-04 05:39 UTC, harlanhaskins requested changes

2017-03-04 05:39 UTC, harlanhaskins commented on Sources/IRGen/ValueIRGen.swift
> +    let ptr = globalString.ptr.constGEP(indices: indices)
I think this can just be a `load` no?

2017-03-04 05:39 UTC, harlanhaskins commented on Sources/IRGen/ValueIRGen.swift
> +    guard let stringTypeDecl = context.type(named: "String") else { fatalError("use of string literal without stdlib String") }
Maybe we should make this a property of `ASTContext` like we discussed

2017-03-04 05:39 UTC, harlanhaskins commented on Sources/IRGen/ValueIRGen.swift
> +    guard let inititalizer = stringTypeDecl.initializers.first(where: { initializer in
I'd prefer not to use string comparison for this. It can get sloppy.

2017-03-05 00:38 UTC, harlanhaskins commented on stdlib/String.tr
> +func trill_fatalError(_ message: String) {
I think this should be spelled `fatalError(_:)`

2017-03-05 00:39 UTC, harlanhaskins commented on stdlib/bytearray.tr
> +      trill_fatalError("index out of bounds".cString())
Probably don't need this now

2017-03-05 00:39 UTC, harlanhaskins commented on Sources/Semantic Analysis/Sema.swift
> -  func candidate(forArgs args: [Argument], candidates: [FuncDecl]) -> FuncDecl? {
Ha! Probably should've removed this weeks ago.

2017-03-05 00:50 UTC, harlanhaskins commented on stdlib/String.tr
> +func trill_fatalError(_ message: String) {
When we get default arguments, this will be fun.

2017-03-05 22:58 UTC, harlanhaskins commented
This will need updating once we merge #36

2017-03-07 02:23 UTC, segiddins commented
Still uses a string compare, but other than that using the stdlib is now much more robust!

2017-03-07 02:35 UTC, segiddins commented
A _super_ nice side effect to this is that `-emit ast` no longer includes the stdlib unless you add `-show-imports`!

2017-03-07 02:41 UTC, harlanhaskins commented
🎉 Why is that?

2017-03-07 02:45 UTC, segiddins commented
> Why is that?
Because you no longer explicitly pass in the stdlib files to be compiled

2017-03-07 02:46 UTC, harlanhaskins commented
Oh! Right! 😃

2017-03-07 03:04 UTC, harlanhaskins requested changes
I'm ridiculously excited to merge this.

2017-03-07 03:04 UTC, harlanhaskins commented on Sources/Base/ASTContext.swift
> +      if case .pointer(type: DataType.int8) = canTy {
`DataType` is `Equatable` so you can rewrite this as:

```swift
if [.string, .pointer(type: .int8)].contains(canTy) {
  expr.type = contextualType
  return true
}
```

2017-03-07 03:04 UTC, harlanhaskins commented on Sources/Infrastructure/Utilities.swift
> +let runtimeFramework: Bundle? = Bundle(identifier: "com.harlanhaskins.trillRuntime")
We might want to rename this to `com.trill-lang.trillRuntime`

2017-03-07 03:04 UTC, harlanhaskins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  stdlib = true;
This should be flipped, no?

```c++
cl::opt<bool> noStdlib("no-stdlib", cl::desc("Don't include the trill standard library"), cat);
```

2017-03-07 03:04 UTC, harlanhaskins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +    static_cast<bool>(stdlib),
No need to `static_cast` here, and if this is flipped we should just `!` it.

2017-03-07 03:04 UTC, harlanhaskins commented on Sources/trill/main.swift
> +    driver.add("Lexing and Parsing the trill standard library") { context in
Pass title is kinda long. Maybe just `Parsing Standard Library`

2017-03-07 03:07 UTC, segiddins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  stdlib = true;
I don't entirely understand the format used by the default bool parser, so I'm not sure -- we want both `-stdlib` and `-no-stdlib` to work (and not require `-no-no-stdlib`).

2017-03-07 03:08 UTC, harlanhaskins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  stdlib = true;
`cl::opt` will automatically marshall to and from `bool`

What would we need `-stdlib` for? That should be the default.

2017-03-07 03:10 UTC, segiddins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  stdlib = true;
It is the default, but you still want it so you can override an earlier `-no-stdlib`

2017-03-07 03:11 UTC, harlanhaskins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  stdlib = true;
I don't necessarily think that's a priority for trill 😅 I don't know of anybody who's generating build flags for trill files...

2017-03-07 03:18 UTC, harlanhaskins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  stdlib = true;
But if you'd prefer to have a `no-stdlib` flag, then that's fine.

2017-03-07 03:19 UTC, segiddins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  cl::HideUnrelatedOptions(category);
this means `trill -help` will only print our flags, and not all the ones inherited from LLVM

2017-03-07 03:25 UTC, harlanhaskins commented on Sources/LLVM Wrappers/LLVMWrappers.cpp
> +  cl::HideUnrelatedOptions(category);
Yep, which is great!

2017-03-07 05:27 UTC, harlanhaskins approved these changes

2017-03-07 05:27 UTC, harlanhaskins commented
:shipit:!!!!!!!!!!!!! (once CI passes)

2017-03-07 06:13 UTC, segiddins commented
🚢

2017-03-07 06:13 UTC, merged